export enum ExceptionMessageCode {
  REFRESH_EXPIRED_TOKEN = 'REFRESH_EXPIRED_TOKEN',
  ACCESS_EXPIRED_TOKEN = 'ACCESS_EXPIRED_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_OR_PASSWORD_INVALID = 'EMAIL_OR_PASSWORD_INVALID',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',
  USER_LOCKED = 'USER_LOCKED',
  USER_BLOCKED = 'USER_BLOCKED',

  // for frontend
  CLIENT_OR_INTERNAL_ERROR = 'CLIENT_OR_INTERNAL_ERROR',

  FILE_STRUCTURE_NOT_FOUND = 'FILE_STRUCTURE_NOT_FOUND',

  // for backend general
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  HTTP_EXCEPTION = 'HTTP_EXCEPTION',

  MISSING_TOKEN = 'MISSING_TOKEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
}
