export enum ExceptionMessageCode {
  REFRESH_EXPIRED_TOKEN = 'REFRESH_EXPIRED_TOKEN',
  ACCESS_EXPIRED_TOKEN = 'ACCESS_EXPIRED_TOKEN',

  // for frontend
  CLIENT_OR_INTERNAL_ERROR = 'CLIENT_OR_INTERNAL_ERROR',
}
